apiVersion: apps/v1
kind: Deployment

metadata:
  name: asterisk-cnf
  namespace: !!string $NAMESPACE
  labels:
    app.kubernetes.io/name: asterisk-cnf
    app.kubernetes.io/instance: asterisk-cnf-$NAMESPACE

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asterisk-cnf
      app.kubernetes.io/instance: asterisk-cnf-$NAMESPACE
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asterisk-cnf
        app.kubernetes.io/instance: asterisk-cnf-$NAMESPACE
      annotations:
        k8s.v1.cni.cncf.io/networks: data-plane # NetworkAttachmentDefinition
    spec:
      containers:
      - name: all-in-one
        image: $REGISTRY_URL/asterisk-cnf
        imagePullPolicy: Always
        #image: andrius/asterisk
        #image: dougbtv/asterisk14

---

apiVersion: v1
kind: Service

metadata:
  name: asterisk-cnf-udp
  namespace: !!string $NAMESPACE
  labels:
    app.kubernetes.io/name: asterisk-cnf
    app.kubernetes.io/instance: asterisk-cnf-$NAMESPACE

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: asterisk-cnf
    app.kubernetes.io/instance: asterisk-cnf-$NAMESPACE
  ports:
  - { name: sip, protocol: UDP, targetPort: 5060, port: 5060 }
  - { name: rtp0, protocol: UDP, targetPort: 10000, port: 10000 }
  - { name: rtp1, protocol: UDP, targetPort: 10001, port: 10001 }
  - { name: rtp2, protocol: UDP, targetPort: 10002, port: 10002 }
  - { name: rtp3, protocol: UDP, targetPort: 10003, port: 10003 }
  - { name: rtp4, protocol: UDP, targetPort: 10004, port: 10004 }
  - { name: rtp5, protocol: UDP, targetPort: 10005, port: 10005 }
  - { name: rtp6, protocol: UDP, targetPort: 10006, port: 10006 }
  - { name: rtp7, protocol: UDP, targetPort: 10007, port: 10007 }
