# https://kubevirt.io/api-reference/v0.27.0/definitions.html#_v1_virtualmachine

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine

metadata:
  name: asterisk-vnf
  namespace: !!string $NAMESPACE

spec:
  running: true
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: asterisk-vnf
        app.kubernetes.io/instance: asterisk-vnf-$NAMESPACE
    spec:
      domain:
        # Multithreadedness breaks the machine (because of nested virtualization?)
        #cpu:
        #  cores: 2
        #  threads: 4
        resources:
          requests:
            memory: 1024M
        devices:
          disks:
          - name: containerdisk
            disk: {}
          - name: cloudinitdisk
            disk: {}
          interfaces:
          - name: control-plane
            bridge: {}
          - name: data-plane
            bridge: {}
      networks:
      - name: control-plane
        pod: {}
      - name: data-plane
        multus:
          networkName: data-plane # NetworkAttachmentDefinition
      volumes:
      - name: containerdisk
        containerDisk:
          image: $REGISTRY_URL/asterisk-vnf
          imagePullPolicy: Always
      - name: cloudinitdisk
        cloudInitNoCloud:
          userDataBase64: !!string $CLOUD_CONFIG

---

apiVersion: v1
kind: Service

metadata:
  name: asterisk-vnf-tcp
  namespace: !!string $NAMESPACE
  labels:
    app.kubernetes.io/name: asterisk-vnf
    app.kubernetes.io/instance: asterisk-vnf-$NAMESPACE

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: asterisk-vnf
    app.kubernetes.io/instance: asterisk-vnf-$NAMESPACE
  ports:
  - name: ssh
    protocol: TCP
    targetPort: 22
    port: 22

---

apiVersion: v1
kind: Service

metadata:
  name: asterisk-vnf-udp
  namespace: !!string $NAMESPACE
  labels:
    app.kubernetes.io/name: asterisk-vnf
    app.kubernetes.io/instance: asterisk-vnf-$NAMESPACE

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: asterisk-vnf
    app.kubernetes.io/instance: asterisk-vnf-$NAMESPACE
  ports:
  - { name: sip, protocol: UDP, targetPort: 5060, port: 5060 }
  - { name: rtp0, protocol: UDP, targetPort: 10000, port: 10000 }
  - { name: rtp1, protocol: UDP, targetPort: 10001, port: 10001 }
  - { name: rtp2, protocol: UDP, targetPort: 10002, port: 10002 }
  - { name: rtp3, protocol: UDP, targetPort: 10003, port: 10003 }
  - { name: rtp4, protocol: UDP, targetPort: 10004, port: 10004 }
  - { name: rtp5, protocol: UDP, targetPort: 10005, port: 10005 }
  - { name: rtp6, protocol: UDP, targetPort: 10006, port: 10006 }
  - { name: rtp7, protocol: UDP, targetPort: 10007, port: 10007 }
